#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap $HOME"/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

# wallpaer
~/.fehbg &

# key
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx

fcitx5 -d &


greenclip &
picom &

# for virtal machine
if [ "$(systemd-detect-virt)" != "none" ]; then
    if command -v spice-vdagent >/dev/null 2>&1; then
        spice-vdagent &
    fi
fi

exec fluxbox
