# Assign windows and applications to workspaces.
#assign [class="Slack"] workspace $ws10

assign [class="discord"] workspace $ws10
for_window [class="discord"] move to workspace $ws10, focus

assign [class="obsidian"] workspace $ws1
for_window [class="obsidian"] move to workspace $ws1, focus

# Launch and focus applications.
bindsym $mod+shift+b exec --no-startup-id firefox

bindsym $mod+shift+s exec --no-startup-id discord, \
    workspace number $ws9, \
    workspace number $ws10, \
    [class="discord"] focus

bindsym $mod+shift+w exec --no-startup-id obsidian, \
    workspace number $ws1, \
    workspace number $ws2, \
    [class="obsidian"] focus
